# Workflow setup for building Native Android project
workflows:
  android-app: # workflow ID
    name: ToDoApp # workflow name
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - build/outputs/**/**/*.apk
